name: Custom Github Docker Action
description: Call API and get user name

inputs:
  chat:
    description: Telegram chat ID
    required: true
  token:
    description: Telegram API token
    required: true
  text:
    description: Telegram message
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.chat }}
    - ${{ inputs.token }}
