name: Custom Github Docker Action
description: Call API and get user name

inputs:
  chat:
    description: Telegram chat ID
    required: true
  token:
    description: Telegram API token
    required: true
  result:
    description: Result (success, failure, skipped, failure)
    required: true
    default: success

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.chat }}
    - ${{ inputs.token }}
