name: github-actions-example

on: push

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run job-one"
          exit 1

  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Run job-two"
        echo "Function success()"

  job-three:
    needs: [job-one, job-two]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Run job-three"
        echo "Function failure()"

  job-four:
    needs: [job-one, job-two, job-three]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Run job-four"
        echo "Function always()"
        echo "Result job-one: ${{ needs.job-one.result }}"
        echo "Result job-two: ${{ needs.job-two.result }}"
        echo "Result job-three: ${{ needs.job-three.result }}"
