name: github-actions-example

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        id: step-one
        # задаем имя и значение output для этого шага
        run: echo "::set-output name=step-one-output::hello from step one"

      - name: Step two
        id: step-two
        # задаем имя и значение output для этого шага
        run: echo "::set-output name=step-two-output::hello from step two"
        # получаем досуп к значению output первого шага
        run: echo Step one output ${{ steps.step-one.outputs.step-one-output }}

      - name: Step three
        id: step-three
        # задаем имя и значение output для этого шага
        run: echo "::set-output name=step-three-output::hello from step three"
        # получаем досуп к значению output первого шага
        run: echo Step one output ${{ steps.step-one.outputs.step-one-output }}
        # получаем досуп к значению output второго шага
        run: echo Step two output ${{ steps.step-two.outputs.step-three-output }}
