name: github-actions-example

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        id: step-one
        # steps.step-one.conclusion == skipped
        if: ${{ false }}
        run: echo "run step one"

      - name: Step two
        id: step-two
        # steps.step-one.conclusion == failure
        run: |
          echo "run step two"
          echo " step one conclusion = ${{ steps.step-one.conclusion }}"
          [[ $RANDOM % 2 ]] && exit 1 || exit 0

      - name: Step three
        id: step-three
        if: ${{ always() }}
        run: |
          echo "run step three"
          echo " step two conclusion = ${{ steps.step-two.conclusion }}"

      - name: Step four
        id: step-four
        if: ${{ failure() }}
        run: |
          echo "run step three"
          echo " step two conclusion = ${{ steps.step-two.conclusion }}"
