name: Test custom docker action

on: [push]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "do some job"
          sleep 10
          echo "job complete"
          exit $(( $RANDOM % 2 ))

  report:
    needs: some-job
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      #- uses: tokmakov/telegram-docker-action@master
      - uses: tokmakov/github-actions-example@master
        with:
          chat: '425435270'
          token: '5205276228:AAHDqptF9UE5TSVyy5-VafpHf0KxBFZskBo'
          result: ${{ needs.some-job.result }}
