name: Test custom docker action

on: [push]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "do some job"
          sleep 5
          echo "job complete"
          rand_number=$(( $RANDOM % 2 ))
          echo "rand_number=$rand_number"
          exit $(( $rand_number % 2 ))

  report:
    needs: some-job
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      #- uses: tokmakov/telegram-docker-action@master
      - uses: tokmakov/github-actions-example@master
        with:
          chat: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          result: ${{ needs.some-job.result }}
